### ISSUE TITLE
2 errors whenever i try to open any AHK with webview2. 

### ISSUE THREAD

**Issue by akselfoley** [thqby/ahk2_lib#12]
So WebView2.ahk gives me these errors:

Error: Parameter #1 of ObjAddRef is invalid.

▶	060: DllCall('user32\GetClientRect', 'ptr', hwnd, 'ptr', RECT := Buffer(16)), ObjAddRef(createdController)

Error: Parameter #2 of ComCall is invalid.

▶	169: Return A_PtrSize = 8 ? ComCall(6, this, 'ptr', Value) : ComCall(6, this, 'int64', NumGet(Value, 'int64'), 'int64', NumGet(Value, 8, 'int64'))

This version:
/************************************************************************
 * @description Use Microsoft Edge WebView2 control in ahk
 * @file WebView2.ahk
 * @author thqby
 * @date 2022/11/26
 * @version 1.0.27
 * @webview2version 1.0.1072.54
 ***********************************************************************/

The code:
#Requires AutoHotKey v2.0-
#Include lib\WebView2.ahk

main := Gui()
main.Show(Format('w{} h{}', A_ScreenWidth * 0.6, A_ScreenHeight * 0.6))
main.Show()

wvc := WebView2.create(main.hwnd)
wv := wvc.CoreWebView2
wv.Navigate("https://www.vg.no")

**Comment by thqby** [comment]
Check whether edge runtime is installed

**Comment by thqby** [comment]
It may be caused by the system environment.

**Comment by akselfoley** [comment]
I've checked on both computers I am testing.

The errors above is from the a computer running .ahk.

But I've also created an .exe to run together with \lib\*

So get a new error there:
![image](https://user-images.githubusercontent.com/21128136/227139423-fc28f6cf-6246-4a73-ab51-256a14902fcc.png)

▶	072: If (R := DllCall(dllPath '\CreateCoreWebView2EnvironmentWithOptions', 'str', edgeruntime, 'str', datadir || RegExReplace(A_AppData, 'Roaming$', 'Local\Microsoft\Edge\User Data'), 'ptr', options, 'ptr', EnvironmentCompletedHandler, 'uint'))



Installation status is the same for both:
![image](https://user-images.githubusercontent.com/21128136/227139587-7769d22a-e786-4807-98b0-260c9e5ad02c.png)

**Comment by akselfoley** [comment]
Can you provide the best structure? :) 

This is my current structure:
![image](https://user-images.githubusercontent.com/21128136/227142953-6ce7d09f-7ac0-4a2d-b5ed-6fb7c17e4e7b.png)

![image](https://user-images.githubusercontent.com/21128136/227143000-f219383b-3646-43b5-b3bf-0d63edacdbca.png)

**Comment by thqby** [comment]
The above directory should not have this error.
My directory is consistent with this repository.

![image](https://user-images.githubusercontent.com/28240311/227147254-417bb1c6-00e9-4a14-bb2c-1bfb194d989c.png)

**Comment by akselfoley** [comment]
How does it know to use D:\Documents\Autohotkey\Lib to look for <Webview2\Webview2> ?

**Comment by thqby** [comment]
https://www.autohotkey.com/docs/v2/Scripts.htm#lib

This is User library.

**Comment by akselfoley** [comment]
But for this to work it should be enough to have:

#Include WebView2\WebView2.ahk

Where the webview2 folder looks like this:
![image](https://user-images.githubusercontent.com/21128136/227211699-d75a7f17-44ba-42a2-adc8-fce4f6abe10e.png)

I will create an .exe from the .ahk, and run it on a computer that dont have AHK installed. 

Any suggestions?

**Comment by thqby** [comment]
Library location priority order, Local library > User library > Standard library.

After the script is compiled, `A_LineFile` will change and need to be adjusted according to the actual situation.

**Comment by thqby** [comment]
yes

**Comment by thqby** [comment]
What is the Edge Webview2 Runtime version?

My current version is 111.0.1661.51

**Comment by akselfoley** [comment]
I have the same version installed. 

I guess I’ll have to walk away from this and keep the current ahi that opens a url in Edge kiosk mode. 

Thanks for trying :)

**Comment by thqby** [comment]
What error? dll file in incorrect path?
