### ISSUE TITLE
Is there a limit to the Page Evaluate value?

### ISSUE THREAD

**Issue by sousvideonlow** [thqby/ahk2_lib#22]
`VarSetStrCapacity(&variable, 5120000)
    Page := xCh.GetPageBy("url", "someurl","contains")
    variable:=Page.Evaluate("document.querySelectorAll('#someid')[0].innerText")["value"]`

Variable seems to be truncated. If I open developer tools and run in console

document.querySelectorAll('#someid')[0].innerText

I get the full string which is about 100KB of text.

**Comment by thqby** [comment]
The Chrome DevTools Protocol (CDP) may have limitations.
