### ISSUE TITLE
ws-min.ahk event parameter is a string

### ISSUE THREAD

**Issue by Lexikos** [thqby/ahk2_lib#23]
In the usage example of ws-min.ahk, there is `Message: (self,event)=>MsgBox(event.data)`, but `event` is actually a JSON string and therefore has no `data` property.

I don't know why you would bother to stringify the Event object.

**Comment by thqby** [comment]
Since this is a com object, people who are not familiar with this will not know that there are those properties, but I forgot to update the usage.
