### ISSUE TITLE
#Warn in DllCall variable arr_data

### ISSUE THREAD

**Issue by rafael4129** [thqby/ahk2_lib#25]
when set '#Warn', the variable local arr_data appears to never be assigned a value.

        014: Static ComObjParam := A_AhkVersion < "2" ? "ComObjParameter" : "ComObject"
	017: arr := ComObjArray(0xC, 1)
▶	019: DllCall("oleaut32\SafeArrayAccessData", "ptr", ComObjValue(arr), "ptr*", arr_data)
	021: Return {ref: %ComObjParam%(0x400C, arr_data), _: arr, base: base}
	022: }

Using AHK 2.04 an latest version of WebView2

**Comment by thqby** [comment]
I didn't write these codes.
