### ISSUE TITLE
AHK 2.0.4 Error in WebView2.ahk line 458 ComVar(object)

### ISSUE THREAD

**Issue by rafael4129** [thqby/ahk2_lib#26]
AHK 2.0.4 Error in WebView2.ahk line 458
Lib\Webview2\WebView2.ahk (458) : ==> Too many parameters passed to function.
     Specifically: ComVar(object)

AHK Code:
  #Requires AutoHotKey v2.0+
  SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.
  #Include <Webview2\WebView2>
  
  main := Gui()
  main.Show("w1200 h1500")
  wv:= WebView2.create(main.Hwnd)
  wv.CoreWebView2.Navigate("https://www.google.com")
Return

**Comment by thqby** [comment]
https://github.com/thqby/ahk2_lib/blob/master/ComVar.ahk

That's what I'm using.
