### ISSUE TITLE
Minimal working example for Socket.Ahk

### ISSUE THREAD

**Issue by EstZw3i** [thqby/ahk2_lib#27]
Hi, I'm trying to work with Socket.ahk via named pipes for existing compatibility with my existing codebase but I have trouble setting it up. I'm unfamiliar with socket technology so there's that as well.

From my limited understanding of the source code. I have set up something like this
### Server 
```
class TestServer extends Socket.Server {
    onREAD(wp){
        MsgBox "On Read"    
    }
    onCONNECT(wp){
        MsgBox "On Connect"
    }
}

server := TestServer(,"\\.\pipe\testPipe")
```

### Client
```
class TestClient extends Socket.Client {
    onREAD(data) {
        MsgBox("Client Read")
    }
    onWRITE(data){
        MsgBox "Client Write"
    }
}

tClient := TestClient("\\.\pipe\testPipe")
tClient.SendText("hi")
```

I assume that the server opens up the socket for listening via `TestServer(,"\\.\pipe\testPipe")` while the client connects to this listening port via `TestClient("\\.\pipe\testPipe")`. I'm definitely missing something here as this clearly doesn't work. It would be great if you could provide a minimal working example for both Server and Client classes so I know what the initial setup looks like. 

I also happen to stumble across this [AHK forum post](https://www.autohotkey.com/boards/viewtopic.php?p=503678#p503678) but the code looks to be tailored towards communicating with LSP server which isn't my use case. I also notice the method `static Call(path?, port := 1219)` and the implementation doesn't seem to align with what I understood as it creates a server socket rather than a client socket.

**Comment by thqby** [comment]
```
#Include <Socket>
class TestServer extends Socket.Server {
	onACCEPT(err) {
		this.client := this.AcceptAsClient()
		this.client.onREAD := onread
		onread(this, err) {
			MsgBox("receive from client`n" this.RecvText())
			this.SendText('hello')
		}
	}
}

server := TestServer(, "\\.\pipe\testPipe")

class TestClient extends Socket.Client {
	onREAD(err) {
		MsgBox("receive from server`n" this.RecvText())
	}
}
Persistent
tClient := TestClient("\\.\pipe\testPipe")
tClient.SendText("hi")
```



> I also happen to stumble across this [AHK forum post](https://www.autohotkey.com/boards/viewtopic.php?p=503678#p503678) but the code looks to be tailored towards communicating with LSP server which isn't my use case.

I tried to connect to the LSP server through the named pipe, but couldn't establish a connection to the nodejs end, while there was no problem between ahk.

**Comment by EstZw3i** [comment]
Thank you for your time and the quick response. I got it working on my side too.

This particular line of code (`this.client.onREAD := onread`) looks a bit odd to read for me personally but I guess it implements an event handler on the client socket whenever the clients sends something? I do have additional questions if you don't mind the length

### 1. How do I close the socket for the following scenarios
	1. Disconnecting the socket Client side after connection
	2. Forcefully disconnecting the client from server side
    3. Closing the server socket 

I assume I should just remove the reference/pointer to those sockets and the corresponding __Delete method will be called accordingly for disposal?

### 2. Does this library fully allow asynchronous event handling
   Normal Named Pipe servers with DLL call to `ConnectNamedPipe` will block the execution of the rest of the code and this proves to be a problem since I have a GUI running in my AHK application. I plan to fully refactor my codebase from using named pipes to socket depending on which is easier to maintain.

### 3. What are the relevant Events that I should handle for Server/Client in Named pipes or Pure Socket(in the future)
I assume only these are relevant for now? I'm only communicating via stringified JSON data between server and client 

1. Client : onREAD
2. server : onACCEPT
3. Accepted client : onREAD

### 4. My Codebase isn't really communicating between 2 AHK Applications but AHK <-> C# so my solution is something like this
    1. AHK -> C#, using Named Pipes
    2. C# -> AHK, using WM_COPYDATA 

I would rather have both side use the same method of communication but setting up named pipe server on AHK proves to be tricky as what  I mentioned on #2. I haven't tried using this library to talk with my C# named pipe server yet so that's something I'll try later on. 

This is a bit out of scope but if I want to implement the socket on C# I guess [this](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socket?view=net-7.0) should be the class I'm working with? No worries if you are unsure about it as I'll try it out myself once I get things setup on AHK.  

Are there any other platforms that I could contact you since opening an issue for questions is a bit strange to me.

**Comment by thqby** [comment]
> ### 1. How do I close the socket for the following scenarios
> I assume I should just remove the reference/pointer to those sockets and the corresponding __Delete method will be called accordingly for disposal?

Yes, or call `__Delete` method to close.
If there is an onclose method, it will be triggered when the other end is disconnected.

> ### 2. Does this library fully allow asynchronous event handling

To implement any event, enable asynchronous mode, otherwise it is synchronous mode. If the `onconnect` method is not implemented, the connection is synchronously blocked.

> ### 3. What are the relevant Events that I should handle for Server/Client in Named pipes or Pure Socket(in the future)
> I assume only these are relevant for now? I'm only communicating via stringified JSON data between server and client

Depending on the requirements, `onread` and `onclose` are generally implemented, and the server also needs to implement `onaccept`.

> Are there any other platforms that I could contact you since opening an issue for questions is a bit strange to me.

autohotkey.com
But I didn't publish a special topic for the library

**Comment by EstZw3i** [comment]
Alright, big thanks for the help.

**Comment by skygate2012** [comment]
> But I didn't publish a special topic for the library

You should publish one! I struggled to get the library working until seeing your example.

**Comment by yzqiang** [comment]
@thqby How to support TLS with your wonderful Socket library?
Thanks very much.

**Comment by yzqiang** [comment]
I have a TCP link: hwsockapp.longhuvip.com with port: 14000.
But I am refused by the server because of some TLS reason.

**Comment by thqby** [comment]
`client.StartTLS(TLSAuth(domian))`

**Comment by yzqiang** [comment]
@thqby 
Download is my code.
`#Include Socket.ahk
#Include TLSAuth.ahk

domain := "hwsockapp.longhuvip.com"
tls := TLSAuth(domain)

class TestClient extends Socket.Client {
	onREAD(err) {
		OutputDebug("receive from server`n" this.RecvText())
	}
}
Persistent
tClient := TestClient(domain, 14000, 3, 3)
tClient.StartTLS(tls)`
But before I StartTls, the server has refused me already.
`(10013) 以一种访问权限不允许的方式做了一个访问套接字的尝试。
`

**Comment by thqby** [comment]
Why is the type set to `raw=3` and the protocol set to `rfcomm=3`?

**Comment by yzqiang** [comment]
> Why is the type set to `raw=3` and the protocol set to `rfcomm=3`?
@thqby I don't know TCP protocol at all. I just tried every possible combination. 
I changed IPROTO to 6, but the result is the same.
![{C9310CB3-F95B-492F-8525-BEC67C3E67D0}](https://github.com/user-attachments/assets/6f9ca57f-ccb2-4f0b-a918-06148b92e189)

**Comment by thqby** [comment]
In most cases, parameters 3 and 4 do not need to be specified.

**Comment by yzqiang** [comment]
> The TCP connection does not need to specify parameters 3 and 4.

@thqby I changed the code to below:
tClient := TestClient(domain, 14000)
Then I got a new wrong message:
![{A3F92198-3484-494E-916B-9B7E1724364C}](https://github.com/user-attachments/assets/699139f8-8bc1-474f-91e8-f15393e60e1a)

**Comment by thqby** [comment]
The server certificate is untrusted. You can specify the TLSAuth parameter to ignore this error.

**Comment by thqby** [comment]
The server certificate is untrusted. You can specify the TLSAuth parameter to ignore this error.

**Comment by yzqiang** [comment]
> The server certificate is untrusted. You can specify the TLSAuth parameter to ignore this error.

The ignore param works well. The wrong message is gone and I have received message from server. Thanks very much.
It's just my first little leap. I will try more. If I meet more problems, I will go on asking here.
Please accept my knees now before my more questions.

**Comment by yzqiang** [comment]
Below is what the terminal output:
![{4DF39EC3-987B-4599-A93F-202C71F2E48C}](https://github.com/user-attachments/assets/48877b35-02a6-4bbc-aff0-785d02d9d570)
But the RecvText function didn't get any text:
`OutputDebug("receive from server`n" this.RecvText())`

**Comment by thqby** [comment]
This is the data required for the tls handshake, including the server certificate and cipher suite. The data is used to initialize the tls context.

For an HTTP request, you first need to send a request packet to the server before the server will respond. For this purpose, using winhttp will be more convenient.

**Comment by yzqiang** [comment]
> This is the data required for the tls handshake, including the server certificate and cipher suite. The data is used to initialize the tls context.
> 
> For an HTTP request, you first need to send a request packet to the server before the server will respond. For this purpose, using winhttp will be more convenient.

This is a TCP link, not a website link.
I will use some TCP support protocol analyze tool to run the whole process first and then use your Socket library to simulate the tool process.
Thanks very much.
