### ISSUE TITLE
Setting AdditonalBrowserArguments results in errors

### ISSUE THREAD

**Issue by The-CoDingman** [thqby/ahk2_lib#30]
I'm attempting to add AdditionalBrowserArguments but it keeps generating an error. 
The error it gives is `Error: This value of type "Integer" has no property named "TargetCompatibleBrowserVersion"` and is occurring on line #857 of the WebView2.ahk file.

I haven't assigned a value to TargetCompatibleBrowserVersion myself, it looks like that's being force assigned at line #39.  I tried enumerating over all the properties for the options at the `get_xxx_str(prop, this, pvalue)` function at line #855, and I can see where the options are being properly passed to this function but the `this` item doesn't have any properties. I even tried to manually pull the property name and value during this function and assign it but received this error: `Error: This value of type "Integer" has no method named "DefineProp"`.  I seem unable to figure out how to fix the issue in the library.

**Comment by thqby** [comment]
Fixed by 3bf893164a1466fd9cba518805991f27cd8e5018
