### ISSUE TITLE
Re: `response := this('Runtime.evaluate',...)` in Chrome.ahk 

### ISSUE THREAD

**Issue by yg-i** [thqby/ahk2_lib#33]
Regarding this line: https://github.com/thqby/ahk2_lib/blob/b72b2d06aa6ee0b55965227f68e97e9170128ee5/Chrome.ahk#L228C28-L228C28

1. Should this be `response := this.Call('Runtime.evaluate', ...)` ? 
2. Why does `response := this('Runtime.evaluate', ...)` work as is?

**Comment by thqby** [comment]
https://www.autohotkey.com/docs/v2/misc/Functor.htm#User-Defined
