### ISSUE TITLE
`This value of type "Chrome.Page" has no property named "readyState"`

### ISSUE THREAD

**Issue by yg-i** [thqby/ahk2_lib#35]
Occasionally, running
```
Chrome().GetPage().Evaluate("window.location.href")['value']
```
throws an error at the line: 
```
if ws.readyState != 1
```
in https://github.com/thqby/ahk2_lib/blob/b72b2d06aa6ee0b55965227f68e97e9170128ee5/WebSocket.ahk#L112C10-L112C10

Error object below. This may be hard to reproduce though. If I figure out how to reliably reproduce I will post the steps over here.

```
{
 "Mode": "Return",
 "Thrown": {
  "Extra": "",
  "File": "C:\\ahk\\Lib\\WebSocket.ahk",
  "Line": 112,
  "Message": "This value of type \"Chrome.Page\" has no property named \"readyState\".",
  "Stack": [
   "C:\\ahk\\Lib\\WebSocket.ahk (112) : [WEBSOCKET_READ_WRITE_COMPLETE] If ws.readyState != 1",
   "> OnMessage",
   ""
  ],
  "What": ""
 },
 "Type": "PropertyError"
}
```

**Comment by thqby** [comment]
Cannot reproduce the issue.
The possible cause is that the chrome object lifetime ends before the websocket message is received.

**Comment by thqby** [comment]
@yg-i 
You can try changing `super.__Delete()` to `super.__Delete(), Sleep(50)`.

**Comment by yg-i** [comment]
> @yg-i You can try changing `super.__Delete()` to `super.__Delete(), Sleep(50)`.

Thank you! I will give it a try and report back the results.

**Comment by yg-i** [comment]
@thqby thanks. Appears to have been fixed. No occurrence observed in 2 days!

**Comment by edwyn-amador** [comment]
Hey @thqby , I am getting the same error

![image](https://github.com/thqby/ahk2_lib/assets/36249854/d196624d-561c-4f52-a1b7-26edf268273c)

Previously in Websocket.ahk 1.0.3 I modified line 127:

`if (ws.readyState != 1)
                     return`

To this:

`if (ws.HasProp("readyState") && ws.readyState != 1 || !ws.hasProp("recdata"))
                     return`
						
As I was experiencing this issue and seemed that was enough. Now after updating Websocket.ahk to 1.0.6 I am experiencing same issue again, so probably something like that would be enough to fix this.

**Comment by thqby** [comment]
At this point, the object has been destroyed, and retrieving the object's properties may produce unexpected results.

**Comment by edwyn-amador** [comment]
Yes, that's why that line avoids trying to access the "readyState" property. But now it seems to me that a delay like the one you suggested could be more ideal as it would avoid missing executing the actions set by the user after calling a method.
