### ISSUE TITLE
RapidOcr最新版有问题，无法使用啊

### ISSUE THREAD

**Issue by davidWeiZhou** [thqby/ahk2_lib#36]
老版没问题，2023/01/12那一版的，没任何问题，最新版的，在不编译的情况下，直接跑脚本是没问题的，能正常用，但是，一旦编译成exe，就没法正常使用了，有时候它又可以用，然后多调用几次就不行了，直接导致exe崩溃退出了，请修复一下哈，感谢！

老版的地方调用：RapidOcr.__cbobj，新版的被你改了，不知道是不是这里出问题了。

https://www.autohotkey.com/boards/viewtopic.php?f=27&t=117615&hilit=RapidOcr

**Comment by thqby** [comment]
删除  https://github.com/thqby/ahk2_lib/blob/master/RapidOcr/RapidOcr.ahk#L180-L187
