### ISSUE TITLE
[Webview2] Add example for bypassing CORS?

### ISSUE THREAD

**Issue by skygate2012** [thqby/ahk2_lib#44]
Can you add an example of using local file and bypassing CORS in the examples? I found this line but don't know where to supply it.
`HOST_RESOURCE_ACCESS_KIND := { DENY: 0, ALLOW: 1, DENY_CORS: 2 }`

**Comment by thqby** [comment]
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2?view=webview2-winrt-1.0.2088.41#setvirtualhostnametofoldermapping

I haven't used this. Here's the documentation.

**Comment by skygate2012** [comment]
Reading the docs, I guess that's not what I thought it was. I need to provide this flag `--disable-web-security` to the EnvironmentOptions so that local html files can call APIs on the internet. Can you show me how?

**Comment by thqby** [comment]
```
WebView2.create(hwnd, , , , , { AdditionalBrowserArguments: '--disable-web-security' })
```

**Comment by skygate2012** [comment]
Thanks! That worked like a charm.
