### ISSUE TITLE
[WebView2] New version of library gives error when compiled

### ISSUE THREAD

**Issue by tomkahn** [thqby/ahk2_lib#49]
Here is a simple [example](https://e.pcloud.link/publink/show?code=XZU0tnZfdV9TWp1epVQv6Vid1dkDXUJrKck) I took from somewhere on the forum.

The code works fine as long as you just run the .ahk file directly.

After compiling the .ahk file into an .exe I get this error:

![image](https://github.com/thqby/ahk2_lib/assets/38276038/a4021c02-f92a-41cf-b496-490e1006412d)

It also works fine if you use an older version of your library (1.0.26 from 2022/01/16 as opposed to 1.0.31 from 2023/11/20). I put the older one for comparison into the lib_old folder as well.

I'm using AHK v.2.0.11 U64.

I stumbled across this issue when compiling a bigger project of mine that uses your library. In this case the WebView library doesn't produce an error but simply never loads any website. The older version of the library works fine.

**Comment by thqby** [comment]
I don't think the old version can run properly after compilation, because the default path of the dll has changed after compilation. You need to place the dll file in the root directory of the exe or specify the corresponding dll path in the code.

**Comment by tomkahn** [comment]
Thank you, very helpful. It seems like we fixed this issue in the old version before and that's why it was working.
