### ISSUE TITLE
Is the cpp JSON parser officially part of ahk_lib?

### ISSUE THREAD

**Issue by yg-i** [thqby/ahk2_lib#54]
Hi thqby,

Is your cpp JSON parser officially part of this repo? If not, do you plan on including it at some point?

https://www.autohotkey.com/boards/viewtopic.php?style=1&f=83&t=100602

I've been using it for a year and it has been very reliable and fast!

Just wondering why it's not included. JSON.ahk is also great, but as your testing shows, is almost 10 times slower on stringifying operations.

Thanks,

**Comment by thqby** [comment]
cppJSON is a part of ahk_h, which is not required for the ahk_h I usually use. Additionally, ahk v2 and v2.1 require different dlls.

**Comment by yg-i** [comment]
> cppJSON is a part of ahk_h, which is not required for the ahk_h I usually use. Additionally, ahk v2 and v2.1 require different dlls.

Thanks for the explanation!
