### ISSUE TITLE
After compile to Exe, LoadScript does not work.

### ISSUE THREAD

**Issue by yzqiang** [thqby/ahk2_lib#58]
I use LoadScript library great.
But when I compile my script to Exe using [AHK2EXE](https://github.com/AutoHotkey/Ahk2Exe), it does not work.
I trace the error using DebugView++, I found when AHK run script such as:
LoadScript(script)
There will be error happen and the Exe stop immediately.
Exe is very important for me and other AHK developers.
Please tell me the reason and help us to find a way.
Thanks very much.

**Comment by yzqiang** [comment]
After researching, I found the reason.
Because the Exe infact the LoadScript function must find the LoadScript.ahk script first.
If the AHK file can't be found, there will be error such as that image.
![5fc2550802ab6f1a32ea0a8b2fe69a0](https://github.com/thqby/ahk2_lib/assets/1594490/bd8f3575-5f4e-4dac-bbfc-b7f7237f1d9a)

**Comment by yzqiang** [comment]
I think maybe it's the AHK2Exe error not the LoadScript error.

**Comment by thqby** [comment]
Some dynamic code is executed. After the script is compiled, additional library files need to be placed or embedded in source code.
