### ISSUE TITLE
RapidOcrOnnx.dll GPU support

### ISSUE THREAD

**Issue by Qriist** [thqby/ahk2_lib#60]
Hey there thqby! Is your provided RapidOcrOnnx.dll compiled with GPU support? If it is, how do I tell it to use the GPU? If not, would you please consider doing so?

I've been trying to compile the dll myself but I can't get the prerequisites to install and I have no idea how to solve the errors I'm getting.

Thanks!

**Comment by thqby** [comment]
The current version supports only CPUs. I have tested the directml version on my computer, but no performance advantage.

**Comment by Qriist** [comment]
> The current version supports only CPUs. I have tested the directml version on my computer, but no performance advantage.

Ah that's unfortunate. Thanks for checking it out for me.

In that same vein, are you sure that you compiled the the dll with multithreading enabled?

I ran the following code with a variety of `threads` values:
```
#Requires AutoHotkey v2.0
#Include <RapidOcr>

image := "1.bmp"
threads := 999

param := RapidOcr.OcrParam()
param.doAngle := false

ocr := RapidOcr({ models: A_ScriptDir "\models", numThread: threads },A_ScriptDir "\RapidOcrOnnx.dll")

num := 100
loop num{
    ToolTip(Round((a_index / num)*100,2) "%")
    ocr.ocr_from_file(image, param?)
}
```
I've tried 1,2,4,6,8, and 999 threads, but all of them gave extremely similar (within milliseconds) results. The time varies a little bit per image, but never per thread value per given image. That suggests that the DLL isn't actually running multithreaded. Am I doing something wrong?

**Comment by thqby** [comment]
After applying this commit https://github.com/RapidAI/RapidOcrOnnx/commit/83886d188058633b806258908e25c4aff7e4ee24, on my computer, the number of threads is set to 2 or 3 for the fastest recognition.

**Comment by Qriist** [comment]
I appreciate you looking into that!
