### ISSUE TITLE
Chrome still prompts one to select the chrome profile even after providing full path

### ISSUE THREAD

**Issue by sousvideonlow** [thqby/ahk2_lib#62]
so I examined this line

`		Run(CliEscape(ChromePath) ' --remote-debugging-port=' this.DebugPort ' --remote-allow-origins=*'
			(ProfilePath ? ' --user-data-dir=' CliEscape(ProfilePath) : '')
			(Flags ? ' ' Flags : '') URLString, , , &PID)`

and personally had problems when providing the full profile path.

However, if I ran in windows Run the following, it works correctly
`"C:\Program Files\Google\Chrome\Application\chrome.exe" --remote-debugging-port=9222 --remote-allow-origins=* --profile-directory="Profile 2"`

hence I think the ' --user-data-dir=' could be replaced with '--profile-directory='

and the user has to specific the Default, Profile 1, or Profile 2 as the 4th param

**Comment by thqby** [comment]
This issue cannot be reproduced in edge.

**Comment by sousvideonlow** [comment]
Yes but try in chrome

**Comment by thqby** [comment]
Maybe Google Browsers broke the compatibility.
You can pass additional command-line parameters in the `flags` parameter.

**Comment by sousvideonlow** [comment]
cool will do that thanks
