### ISSUE TITLE
Thread.ahk question

### ISSUE THREAD

**Issue by Descolada** [thqby/ahk2_lib#73]
Hello!
I noticed you have Thread.ahk in your repository which apparently creates a new real thread and uses `CallbackCreate` to create the starting address. To my knowledge this is quite dangerous and can (will?) invalidate g_script, potentially leading to a crash. This is especially true since the `CallbackCreate` doesn't use "Fast" mode. Is there an use for this library that I can't see? Have I understood the risks incorrectly?

**Comment by thqby** [comment]
> Have I understood the risks incorrectly?

You were right. This file was created a long time ago, when I didn't know much about multithreaded environments. Now I have removed it.
