### ISSUE TITLE
RapidOCR，我直接用ocr_from_mat，传入opencv4.8.0 Mat无效，报错

### ISSUE THREAD

**Issue by six7ths** [thqby/ahk2_lib#75]
具体报错如下，请问可能是什么原因呢？

Error: An exception was thrown.

Specifically: 0xc0000005

	---- ..\RapidOcr\RapidOcr.ahk
	084: }
	087: {
▶	087: Return DllCall('RapidOcrOnnx\OcrDetectMat', 'ptr', this, 'ptr', mat, 'ptr', param, 'ptr', RapidOcr.__cb(2 - !allresult), 'ptr', ObjPtr(&res)) ? res : ''
	087: }
	090: {

**Comment by thqby** [comment]
上下文代码呢

**Comment by six7ths** [comment]
bm_buf1 := wgcp0.capture(rect1)

	bb := bm_buf1.cvtBytes(3)
	wid := bb.width, hei := bb.height, pBits := bb.Ptr, Channels := 3 ;通道

	mat := matTest.create(hei, wid, 16, pBits, (wid * Channels + 3) & -4)

**Comment by thqby** [comment]
matTest.create创建的不是裸Mat对象

**Comment by thqby** [comment]
https://github.com/thqby/ahk2_lib/tree/master/opencv

`cv.Mat(...)`

**Comment by six7ths** [comment]
> https://github.com/thqby/ahk2_lib/tree/master/opencv
> 
> `cv.Mat(...)`

我试一下先，昨天我连dll都load不进去，很是抓狂

**Comment by six7ths** [comment]
> https://github.com/thqby/ahk2_lib/tree/master/opencv
> 
> `cv.Mat(...)`

D:\opencv_test copy.ahk (28) : ==> Failed to load DLL.
     Specifically: D:\Tools\opencv_AHK2\opencv_ahk.dll

我dll还是load不进去，用不了啊

**Comment by six7ths** [comment]
> ![{C1F6BBF5-4445-467C-A3C6-841C01C73548}](https://private-user-images.githubusercontent.com/28240311/389530806-160f7c1f-9ba3-47d1-b47c-c3e0cfc6e9a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MzkzMDUsIm5iZiI6MTczMjUzOTAwNSwicGF0aCI6Ii8yODI0MDMxMS8zODk1MzA4MDYtMTYwZjdjMWYtOWJhMy00N2QxLWI0N2MtYzNlMGNmYzZlOWE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDEyNTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmQwMDIzOTY5MTBiN2NkYWQ5YjQ4ZjNhMWIzOGZlYTM0ODM4OGJmZTAzY2NiMTBhYjI5ZDA2NGE0NGFlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IPLRaDmwRzcj2k2cZ1xo5td8ne-57zZlCGmkR_6ca54)

Error: This value of type "Cv_Object" has no property named "CV_8UC3".

**Comment by six7ths** [comment]
> 图片不显示
> 
> opencv中没Cv_Object这个对象

我刚才把这句注释掉，然后可以load进dll了
; #DllLoad "D:\WorkZZ\Tools\opencv_AHK2\opencv_ahk.dll"

但是用下面语句转为mat的图，显示出来不对，只剩几个白色线条，看不到数字和文字了。我看了一下capture的图，是正常的。
我记起来了，下午为什么我用mat.create，就因为，用这个语句，转化的mat，用inshow看不到原图，变成很多白色竖线了。

wid := bm_buf1.width, hei := bm_buf1.height, pBits := bm_buf1.Ptr, Channels := 3 ;通道
mat := cv.Mat(hei, wid, cv2.CV_8UC3, bm_buf1.ptr, bm_buf1.pitch)

**Comment by thqby** [comment]
```
data := wgc.capture([100, 100, 500, 500]).cvtBytes(3)
mat := cv.Mat(data.height, data.width, cv2.CV_8UC3, data.ptr, data.pitch)
```

**Comment by six7ths** [comment]
多谢多谢，又按上面梳理了以下代码，这下都出来了。  至少cv2.CV_8UC3可以扔进rapidocr里，所有内容跟仍bmp一模一样。 真是太感谢了。

**Comment by six7ths** [comment]
再请教一个问题，我对wgc截屏，gdi+复制出来，然后做完后处理，这时再想给rapidocr做ocr，我现在用下面的方法构造出结构化BitmapBuffer，然后给ocr识别，结果却出现1分钟左右出现一次识别异常，纯数字的图片识别出前后的标点符号。很奇怪。请问，是我构造st_bf参数有问题吗？  还有没有其他更方便的方便把pBitmap传递进rapidocr呢？

bm_buf1 := wgcp0.capture(rect1)
pBitmap := Gdip_CreateBitmapFromHBITMAP(bm_buf1.HBITMAP())
；这里对pBitmap做后处理
p_bm_buf := ImagePutBuffer(pBitmap)
NumPut("ptr", p_bm_buf.ptr, "uint", p_bm_buf.size // p_bm_buf.height, "uint", p_bm_buf.width,
"uint", p_bm_buf.height, "uint", 4, "uint", 0, "uint", 0, st_BF := Buffer(40, 0))

**Comment by thqby** [comment]
不知道p_bm_buf是什么结构，看上去没问题

**Comment by six7ths** [comment]
> 不知道p_bm_buf是什么结构，看上去没问题

用的是
 buliasz/AHKv2-Gdip 的库，Gdip_All.ahk里包装的方法；看应该是调用win gdiplus库生成的pBitmap，一个指向Bitmap的指针
这时win32 API的微软解释
https://learn.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicimagingfactory-createbitmapfromhbitmap

Gdip_CreateBitmapFromHBITMAP(hBitmap, Palette:=0)
{
	DllCall("gdiplus\GdipCreateBitmapFromHBITMAP", "UPtr", hBitmap, "UPtr", Palette, "UPtr*", &pBitmap:=0)
	return pBitmap
}
