### ISSUE TITLE
在请教一下，为什么threshhold后生产的新mat 放入rapidocr 会出异常

### ISSUE THREAD

**Issue by six7ths** [thqby/ahk2_lib#76]
bm_buf2 := bm_buf1.cvtBytes(3)
mat := cv.Mat(bm_buf2.height, bm_buf2.width, cv2.CV_8UC3, bm_buf2.Ptr, bm_buf2.pitch)
上面的mat直接放入rapidocr，没有问题
cv.cvtColor(mat, img_gray := cv.MAT(), cv2.COLOR_BGR2GRAY)

这是灰色化，然后
ocr.ocr_from_mat(img_gray, param)

就出一下异常
Error: An exception was thrown.

Specifically: 0xe06d7363

	---- D:\WorkZZ\Tools\RapidOcr\RapidOcr.ahk
	084: }
	087: {
▶	087: Return DllCall('RapidOcrOnnx\OcrDetectMat', 'ptr', this, 'ptr', mat, 'ptr', param, 'ptr', RapidOcr.__cb(2 - !allresult), 'ptr', ObjPtr(&res)) ? res : ''
	087: }
	090: {

The current thread will exit.

**Comment by thqby** [comment]
ocr只接受24位图，opencv灰度图是8位的，OcrDetectMat没在内部做自动转换。
BitmapBuffer也有灰度转换

**Comment by six7ths** [comment]
> ocr只接受24位图，opencv灰度图是8位的，OcrDetectMat没在内部做自动转换。 BitmapBuffer也有灰度转换

好的，多谢，我来试试处理完的8位转24位看。

**Comment by six7ths** [comment]
> ocr只接受24位图，opencv灰度图是8位的，OcrDetectMat没在内部做自动转换。 BitmapBuffer也有灰度转换

多谢，搞定了。 我用
cv.cvtColor(mat, new_img24:=cv.MAT(),cv2.COLOR_GRAY2BGR)

然后OcrDetectMat就没问题了。  多谢多谢

**Comment by six7ths** [comment]
> ocr只接受24位图，opencv灰度图是8位的，OcrDetectMat没在内部做自动转换。 BitmapBuffer也有灰度转换

其实我是要处理颜色，试试threshhold的方法，看网上说，首选要灰度化，然后才能用threshhold

因为这个颜色还比较麻烦， 所以，感觉bitmapbuffer搞不定，才试着用opencv，结果尝试半路中跳异常，排查后发现从灰色化开始，就会导致rapidcor就跳异常了，后面的threshhold那是全部异常，所以特来请教，只请教了灰色化，大致觉得灰色化问题解决了，后面的threshhold应该也不会跳异常了吧。
