### ISSUE TITLE
Please need help

### ISSUE THREAD

**Issue by H5820121** [thqby/ahk2_lib#77]
@thqby
Thanks for the great bbt V2 script.
How can I change the text direction to be right to left (very necessary for RTL languages)?
Thanks!

**Comment by thqby** [comment]
I haven't used bbt and don't know about this yet.

**Comment by H5820121** [comment]
@thqby 
> I haven't used bbt and don't know about this yet.
It's strange, because you're mentioned in the script, it says this:
BTT转v2 by城西 2022.6.18 https://github.com/liuyi91   ：初步测试支持thqby大佬的 v2 beta4
;感谢大佬thqby的悉心指点 https://github.com/thqby/
(And my request is how can I align the texts to the right side?)
Thanks!

**Comment by thqby** [comment]
I've converted some v1 scripts but haven't used them any further.

Use Gdip_SetStringFormatAlign to change the alignment style.

**Comment by H5820121** [comment]
Thank you for your reply!
I would be very grateful if you could please elaborate more on how to use
Gdip_SetStringFormatAlign, and where in the script, and is it also possible
to align to the center?
It will help me a lot
Thank you!

‫בתאריך יום ד׳, 11 בדצמ׳ 2024 ב-1:20 מאת ‪thqby‬‏ ***@***.***
‬‏>:‬

**Comment by H5820121** [comment]
@thqby
Thank you for your reply!
I would be very grateful if you could please elaborate more on how to use
Gdip_SetStringFormatAlign, and where in the script, and is it also possible
to align to the center?
It will help me a lot
Thank you!


‫בתאריך יום ד׳, 11 בדצמ׳ 2024 ב-1:20 מאת ‪thqby‬‏ ***@***.***
‬‏>:‬

**Comment by thqby** [comment]
https://github.com/liuyi91/ahkv2lib-/blob/main/BTT%20v2%E8%BD%AC%E5%86%99%E3%80%902022.06.18%E3%80%91.ahk#L520

https://learn.microsoft.com/en-us/windows/win32/api/gdiplusstringformat/nf-gdiplusstringformat-stringformat-setalignment

**Comment by H5820121** [comment]
@thqby Many thanks!

**Comment by H5820121** [comment]
@thqby 
I checked it,
For some reason unfortunately, Gdip_SetStringFormatAlign(hStringFormat, Align:=0) (line 520) is not aligning to the right.
And what works is just straight to the left, and straight to the center by align:=1.
Could I please bother you to check this?
