### ISSUE TITLE
[child_process.ahk] Encoding issue? 

### ISSUE THREAD

**Issue by marium0505** [thqby/ahk2_lib#78]
I have some weird encoding issues with Norwegian letters.

SimpleCmd  returns the characters correctly, but it fails with the Cmd try. 

I am unsure if the issue is with how the characters are sent to the console or when they are returned from the console, as both the echo message and the result show them incorrectly, which suggest it is one or the other (but haven't been able to figure out which). 

Example 1:
```
	InputString := "echo Special Letters ÆØÅ`n"
	SimpleCmd := child_process(InputString, , { Encoding: "utf-8" })
	SimpleCmd.Wait(), SimpleCmd_Result := Trim(SimpleCmd.stdout.Read(), "`n`r")
```	

Example 2:
```
	Cmd := child_process("cmd.exe", , { Encoding: "utf-8" })
	stdin := Cmd.stdin, stdout := Cmd.stdout, stdout.complete := false
	stdout.onData := (this, str) => RegExMatch(str, "(^|`n)(\s*\w:[^>]*>)$", &m) ?
		this.Append(SubStr(str, this.complete := 1, -m.Len[2])) : this.Append(str)
	write_and_read(cmd := "") {
		(cmd && stdin.Write(cmd), stdin.Read(0))
		while !stdout.complete
			Sleep(-1)
		Data := stdout.Read()
		stdout.complete := false
		return Trim(Data, "`n`r")
	}
	write_and_read(), Cmd_Result := write_and_read(InputString), Cmd.Terminate()
```

Output: 
```
	OutputDebug(Info := Format("Command: `n{}`n`nSimpleCmd_Result: `n{}`n`nCmd_Result: `n{}", Title := Trim(InputString, "`n`r"),SimpleCmd_Result, Cmd_Result))
	MsgBox(Info, Title,0x1000)
```

As you see, the special characters are shown correctly in the msg box (well in the first line and the title, which is from InputString, and in the output of the first attempt, but not in the second attempt.  
![image](https://github.com/user-attachments/assets/411a7c62-5b59-4561-b265-61f1f5c80181)

Any idea what the cause is, and how to fix it?

**Comment by thqby** [comment]
cmd does not use utf-8 by default, you need to execute chcp 65001 to change the code page.

**Comment by marium0505** [comment]
It does, `chcp`  always output: 
`Active code page: 65001` for me, regardless if I have used chcp 65001 before. 

Using chcp 65001  doesn't solve it either.

**Comment by thqby** [comment]
in win11, echo cannot be found as an executable program.

In my test, these characters can be displayed normally. This may be related to the language set by the system.

`chcp 65001> nul`, this can suppress the output.

**Comment by marium0505** [comment]
I'm using w10, and echo gives no error. 
Theres no point using chcp 65001> nul, as the code page is already 65001.

**Comment by thqby** [comment]
> Theres no point using chcp 65001> nul, as the code page is already 65001.

You set UTF-8 as the system default code page?
This happens when I set the system default code page to utf-8.

https://www.autohotkey.com/boards/viewtopic.php?f=81&t=110847
> However, Windows version 1903 added a way for programs to opt in to UTF-8 as the active code page. If the code that was previously dealing with ANSI strings is able to handle UTF-8 correctly, this makes the full range of Unicode characters work with very little effort; otherwise, it can break the program. I won't be enabling it by default because of the implications to compatibility, but users can choose to enable it either by modifying AutoHotkey or by compiling a script with a custom manifest.

**Comment by marium0505** [comment]
The only thing I have done in terms of region/language settings is using Norwegian as the language across the system in the settings app. 

What is usually the system default code page? And how do I eventually change it back (pretty sure I never changed it)?  

I would also like to mention that [teadrinker's](https://www.autohotkey.com/boards/memberlist.php?mode=viewprofile&u=62433) [AsyncStdoutReader Class](https://www.autohotkey.com/boards/viewtopic.php?f=83&t=122732) does not have the issue. 

It is also worth noting that this code also has the expected output: 
`	InputString := "echo Special Letters ÆØÅ`n"
	SimpleCmd := child_process(InputString, , { Encoding: "utf-8" })
	SimpleCmd.Wait(), SimpleCmd_Result := Trim(SimpleCmd.stdout.Read(), "`n`r")
`

**Comment by thqby** [comment]
cmd may not properly decode input from stdin in some cases.
The two examples you sent that work, neither use stdin input.

> What is usually the system default code page? And how do I eventually change it back (pretty sure I never changed it)?

It's set up right here on this setup page you mentioned. For example, I set the locale of my current system to Chinese, so the default code page is cp936.

**Comment by marium0505** [comment]
Ahh, right. 

I tried with the checkbox both checked and unchecked (and restarted after changing it, of course), made no difference. 
Tested on two computers, both on Windows 10.

**Comment by thqby** [comment]
Oh, I don't know. After I set the locale to Norwegian, the cmd showed the active code page as 850, which did not occur.
I don't know if it's related to the older console mode.
https://learn.microsoft.com/en-us/windows/console/legacymode#api-differences

**Comment by marium0505** [comment]
Why close it as completed?

**Comment by thqby** [comment]
This should be a issue with cmd, I have verified that the input and reading are as expected. This issue cannot be solved in this library. You can also use powershell to test it, and there is no such issue.

**Comment by thqby** [comment]
This should be a issue with cmd, I have verified that the input and reading are as expected. This issue cannot be solved in this library. You can also use powershell to test it, and there is no such issue.

**Comment by FuPeiJiang** [comment]
`AttachConsole` -> `WriteConsoleInput` could work but I don't like this solution since you can only attach to one console at a time

`PostMessage`:`WM_CHAR` is my preferred method, I think this should be used for all programs that will "decode" user-input

`WriteFile` should only be used for binary data: example: der encoded

**Comment by thqby** [comment]
> WriteFile should only be used for binary data: example: der encoded

When cmd uses stdin, it seems to work only if the code page is CP_OEMCP, and when I specify utf-8, the output is correct, but cmd cannot handle the input.

@marium0505 You can also try setting the code page of cmd/stdin/stdout to CP_OEMCP.
`oemcp := DllCall('GetOEMCP')`

**Comment by marium0505** [comment]
@thqby I added your recent changes, encoding works as expected now. Thansk for your work/help! :) 

Happy new year!

**Comment by thqby** [comment]
Oddly, The latest update is not intended to solve this issue.

**Comment by thqby** [comment]
@marium0505 
```
cp := child_process('cmd.exe', ,{ stdin: 0, encoding: DllCall('GetOEMCP') })
Sleep(500)
WriteConsoleInput(cp.pid, 'chcp 65001`r')
Sleep(500)
MsgBox(cp.stdout.read())
cp.stdout.setEncoding(65001)
WriteConsoleInput(cp.pid, 'echo 😊`r')
Sleep(500)
MsgBox(cp.stdout.read())
cp.terminate()

WriteConsoleInput(pid := 0, cmd := '') {
	static ir2 := Buffer(40), last_attach_pid := -1, last_attach_hwnd := -1, conin, hStdIn
	static pir2 := NumPut('int64', 0x100000001, 'int64', 1, 'int', 0, 'int64', 1, 'int64', 1, 'int', 0, ir2) - 40
	if pid !== last_attach_pid || DllCall('GetConsoleWindow', 'ptr') !== last_attach_hwnd {
		DllCall('FreeConsole')
		if !pid
			return conin := !last_attach_pid := last_attach_hwnd := -1
		if !DllCall('AttachConsole', 'uint', pid)
			throw OSError()
		conin := FileOpen('CONIN$', 'w'), hStdIn := conin.Handle
		last_attach_pid := pid, last_attach_hwnd := DllCall('GetConsoleWindow', 'ptr') || -1
	}
	loop parse cmd {
		NumPut('ushort', char := Ord(A_LoopField), NumPut('ushort', char, pir2, 14) + 20)
		if !DllCall('WriteConsoleInputW', 'ptr', hStdIn, 'ptr', pir2, 'uint', 2, 'uint*', 0)
			throw OSError()
	}
}
```

**Comment by lmstearn** [comment]
@marium0505: Just curious, does it make any difference when [changing the console font](https://stackoverflow.com/a/17177904/2128797)?
