### ISSUE TITLE
YAML.ahk  stringify 解析错误。

### ISSUE THREAD

**Issue by skelet8801** [thqby/ahk2_lib#8]
将一个Object 转换为Yaml格式的字符串时，  yaml格式错误。

[测试脚本.txt](https://github.com/thqby/ahk2_lib/files/10785120/default.txt)

**Comment by skelet8801** [comment]
311行 中应该为 R+1 吧？   LTrim(CO(value, J, R, F), " `t`n")       -->     LTrim(CO(value, J, R+1, F), " `t`n")

**Comment by thqby** [comment]
改了后有出现其他问题吗
