### ISSUE TITLE
YAML.ahk  解析yaml字符串  出现错误。

### ISSUE THREAD

**Issue by skelet8801** [thqby/ahk2_lib#9]
![20230225_170153](https://user-images.githubusercontent.com/19408530/221348589-ac6de814-19b4-4095-84c0-29d95691fca1.png)

解析 yaml 字符串的时候，Map层级出现错误。
key2/key3 变成了 key1(Map) 的键了。

初步排查原因:
69行中  "else L := I[LL] + (D[LL] is Map)"  修改为  "else L := I[LL]"  就没问题了。 

附:
查看 HotKeyIt 原版的"Yaml.ahk"中，也是 "else L := I[LL]" 。
https://github.com/HotKeyIt/Yaml/blob/ahkV2/Yaml.ahk

[t22_02_问题演示.txt](https://github.com/thqby/ahk2_lib/files/10830640/t22_02_.txt)

**Comment by thqby** [comment]
在某些情况下，层级错误才改的，然而改的还是不行
